name: Build and test Angular web-application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.16.*
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.*
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build -- --prod
    - name: Install forever
      run: npm install forever -g
    - name: Start app
      run: forever start node_modules/@angular/cli/bin/ng serve 
    - name: Sleep for 30 seconds (let the ng serve boot)
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: E2E
      run: npm run e2e:ci